/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.labthink.tools;

import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.labthink.utils.GUIPrintStream;

/**
 *
 * @author Moses
 */
public class ToolsNavigator extends javax.swing.JFrame {

    /**
     * Creates new form ToolsNavigator
     */
    public ToolsNavigator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Fallingdart = new javax.swing.JButton();
        jButton_Infrared = new javax.swing.JButton();
        jButton_ZigbeeSet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton_random = new javax.swing.JButton();
        jButton_checksum = new javax.swing.JButton();
        jButton_UnitConvert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Moses' ToolSet");
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("设备相关工具"));

        jButton_Fallingdart.setText("设备数据计算工具");
        jButton_Fallingdart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FallingdartActionPerformed(evt);
            }
        });

        jButton_Infrared.setText("红外传感器工具");
        jButton_Infrared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InfraredActionPerformed(evt);
            }
        });

        jButton_ZigbeeSet.setText("Zigbee配置工具");
        jButton_ZigbeeSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ZigbeeSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Fallingdart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Infrared, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ZigbeeSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Fallingdart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Infrared)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ZigbeeSet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("常用工具"));
        jPanel2.setToolTipText("");

        jButton_random.setText("随机选择工具");
        jButton_random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_randomActionPerformed(evt);
            }
        });

        jButton_checksum.setText("校验计算工具");
        jButton_checksum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_checksumActionPerformed(evt);
            }
        });

        jButton_UnitConvert.setText("单位转换工具");
        jButton_UnitConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UnitConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_random)
                    .addComponent(jButton_checksum)
                    .addComponent(jButton_UnitConvert))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_random)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_checksum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_UnitConvert)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_randomActionPerformed

        RandomSelect rs = new RandomSelect();
        rs.setVisible(true);
        rs.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rs.setLocationRelativeTo(getOwner());
        this.dispose();
    }//GEN-LAST:event_jButton_randomActionPerformed

    private void jButton_FallingdartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FallingdartActionPerformed

        DeviceResultCompute rs = new DeviceResultCompute();
        rs.setVisible(true);
        rs.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rs.setLocationRelativeTo(getOwner());
        this.dispose();
    }//GEN-LAST:event_jButton_FallingdartActionPerformed

    private void jButton_checksumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_checksumActionPerformed
        //2013.11.07 新增加校验和计算功能

        CheckSumUI rs = new CheckSumUI();
        rs.setVisible(true);
        rs.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rs.setLocationRelativeTo(getOwner());
        this.dispose();
    }//GEN-LAST:event_jButton_checksumActionPerformed

    private void jButton_InfraredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InfraredActionPerformed
        InfraredSimulator rs = new InfraredSimulator();
        rs.initOutput();
        System.setOut(rs.gpstream);
        rs.setVisible(true);
        rs.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rs.setLocationRelativeTo(getOwner());
        System.out.println("Zigbee解析工具输出功能会受到影响，请重新启动或者点击清空重新激活");
        this.dispose();
    }//GEN-LAST:event_jButton_InfraredActionPerformed

    private void jButton_ZigbeeSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ZigbeeSetActionPerformed
        WEXUtil rs = new WEXUtil();
        rs.setVisible(true);
        rs.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rs.setLocationRelativeTo(getOwner());
        this.dispose();
    }//GEN-LAST:event_jButton_ZigbeeSetActionPerformed

    private void jButton_UnitConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UnitConvertActionPerformed
        UnitConverter rs = new UnitConverter();
        rs.initOutput();
        System.setOut(rs.gpstream);
        rs.setVisible(true);
        rs.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rs.setLocationRelativeTo(getOwner());
        System.out.println("Zigbee解析工具输出功能会受到影响，请重新启动或者点击清空重新激活");
        this.dispose();
    }//GEN-LAST:event_jButton_UnitConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToolsNavigator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToolsNavigator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToolsNavigator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToolsNavigator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToolsNavigator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Fallingdart;
    private javax.swing.JButton jButton_Infrared;
    private javax.swing.JButton jButton_UnitConvert;
    private javax.swing.JButton jButton_ZigbeeSet;
    private javax.swing.JButton jButton_checksum;
    private javax.swing.JButton jButton_random;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
